<a href="https://colab.research.google.com/github/22922511/MachineLearningResource/blob/main/One%20Hot%20Encoding/27One%20Hot%20Encoding%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("cars.csv")

In [3]:
df.head(5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [8]:
print(df["brand"].unique())
print(df["brand"].nunique())

['Maruti' 'Skoda' 'Honda' 'Hyundai' 'Toyota' 'Ford' 'Renault' 'Mahindra'
 'Tata' 'Chevrolet' 'Fiat' 'Datsun' 'Jeep' 'Mercedes-Benz' 'Mitsubishi'
 'Audi' 'Volkswagen' 'BMW' 'Nissan' 'Lexus' 'Jaguar' 'Land' 'MG' 'Volvo'
 'Daewoo' 'Kia' 'Force' 'Ambassador' 'Ashok' 'Isuzu' 'Opel' 'Peugeot']
32

#One Hotencoding using pandas k-1

In [13]:
pd.get_dummies(df,columns=["fuel","owner"],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

#One Hotencoding using sklearn k-1

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [33]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder(drop="first")
x_train_new=one.fit_transform(X_train[["fuel","owner"]]).toarray()
x_test_new=one.fit_transform(X_test[["fuel","owner"]]).toarray()

In [37]:
pd.DataFrame(np.hstack((X_train[["brand","km_driven"]].values,x_train_new)))

             0       1    2    3    4    5    6    7    8
0      Hyundai   35000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1         Jeep   60000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
2      Hyundai   25000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3     Mahindra  130000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
4      Hyundai  155000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
...        ...     ...  ...  ...  ...  ...  ...  ...  ...
6497      Ford   35000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
6498    Maruti  120000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
6499      Tata   15000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
6500    Maruti   32500  1.0  0.0  0.0  0.0  1.0  0.0  0.0
6501     Isuzu  121000  1.0  0.0  0.0  0.0  0.0  0.0  0.0

[6502 rows x 9 columns]